### ISSUE TITLE
Historical 1.4.4 build for py39?

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/pendulum-feedstock#27]
As airflow (and some neighboring downstreams) still hard pin to 1.4.4, it would be lovely if said version was available for python 3.9 as a historical branch (gah).

Also, I note that the only remaining pin making this non-`noarch` is for `typing >=3.6,<4.0  # [py<35]`... maybe that could be removed now, and make some of these issues less problematic in the future?

**Comment by ocefpaf** [comment]
This one did not get a py39 migration PR yet but we can do both. We even have a 1.4.4 branch already.

**Comment by xylar** [comment]
I'm happy to take care of making both 1.4.4 and the latest build `master` `noarch: python`.  Thanks for pointing this out, @bollwyvl!

**Comment by bollwyvl** [comment]
Already shipping with it! Thanks for the crazy-fast turnaround!
